### ISSUE TITLE
Back, forward and reload functions are not working when loading cross origin domains within the preview frame

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#190]
When alinea is serving on port 3000 and the website is on port 4500, the back, forward and reload buttons are resulting in the following error:

```
Uncaught DOMException: Blocked a frame with origin "http://localhost:4500" from accessing a cross-origin frame.
    at onClick (http://localhost:4500/config.js?0.7435045589351033:1:14201)
    at HTMLUnknownElement.V (http://localhost:4500/chunk-TONXTO3J.js:9:33008)
    at Object.Ah (http://localhost:4500/chunk-TONXTO3J.js:9:33336)
    at bf (http://localhost:4500/chunk-TONXTO3J.js:9:34297)
    at OC (http://localhost:4500/chunk-TONXTO3J.js:9:34354)
    at Pm (http://localhost:4500/chunk-TONXTO3J.js:9:71068)
    at ET (http://localhost:4500/chunk-TONXTO3J.js:9:71408)
    at Xm (http://localhost:4500/chunk-TONXTO3J.js:9:71516)
    at RT (http://localhost:4500/chunk-TONXTO3J.js:9:71587)
    at http://localhost:4500/chunk-TONXTO3J.js:9:72996
```

![image](https://user-images.githubusercontent.com/1882256/178348652-5b497e4c-471e-47a0-b83d-0a87bb9ce81b.png)

**Comment by benmerckx** [comment]
This is fixed in 0.1.13. If the preview listener is implemented navigation and reloads work.
