### ISSUE TITLE
Typescript error in v 0.3.1

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#281]
```
TypeError: Cannot read properties of undefined (reading 'validate')
    at new Config (file:///D:/.../node_modules/@alinea/core/dist/Config.js:12:17)
    at createConfig (file:///D:/.../node_modules/@alinea/core/dist/Config.js:54:10)
    at file:///D:/.../.alinea/config.js?1670136388594:1173:14
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadConfig (file:///D:/.../node_modules/@alinea/cli/dist/generate/LoadConfig.js:10:19)
    at async generate (file:///D:/.../node_modules/@alinea/cli/dist/Generate.js:50:20)
    at async serve (file:///D:/.../node_modules/@alinea/cli/dist/Serve.js:51:23)
error Command failed with exit code 1.
```

**Comment by cloetensbrecht** [comment]
Problem solved.
I was using an old version of the alinea.config.tsx where the schema was defined within the workspace instead of within the config itself. I moved the schema from the workspace into alinea.createConfig. this is working now.
