### ISSUE TITLE
CMS connection within generateStaticParams() is resulting an error

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#330]
Alinea version: ^0.4.0-preview.32

```
- error node_modules/next/dist/client/components/headers.js (67:14) @ draftMode
- error Error: Invariant: draftMode() expects to have requestAsyncStorage, none available.
    at draftMode (webpack-internal:///(rsc)/./node_modules/next/dist/client/components/headers.js:63:15)
    at NextDriver.connection (webpack-internal:///(rsc)/./node_modules/alinea/dist/core/driver/NextDriver.server.js:44:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _GraphRealm.eval [as resolve] (webpack-internal:///(rsc)/./node_modules/alinea/dist/core/CMS.js:19:25)
    at async getMemberPaths (webpack-internal:///(rsc)/./src/app/[locale]/team/[member]/page.tsx:20:40)
    at async Object.generateStaticParams (webpack-internal:///(rsc)/./src/app/[locale]/team/[member]/page.tsx:31:25)
    at async buildParams (/home/brecht/projects/imecxpand/node_modules/next/dist/build/utils.js:919:36)
    at async /home/brecht/projects/imecxpand/node_modules/next/dist/build/utils.js:936:33
    at async Object.loadStaticPaths (/home/brecht/projects/imecxpand/node_modules/next/dist/server/dev/static-paths-worker.js:88:16) {
  digest: undefined
}
```

![image](https://github.com/alineacms/alinea/assets/1882256/7b530206-c22b-4975-aad6-739eefa027f9)

**Comment by benmerckx** [comment]
Fixed in 43072fa481445ab3a9d95b7baa5f1b4a8032f67f
