### ISSUE TITLE
SqlError: RELEASE `txxx`

### ISSUE THREAD

**Issue by cloetensbrecht** [alineacms/alinea#361]
From time to time I'm receiving the following sql error. The release number is always different.
I have not yet found out exactly when this error message occurs. When I have more info about it, I'll add it to this ticket.

```
SqlError: RELEASE `t127`
│
└──── Error: no such savepoint: t127
    at Object.run (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/alinea/dist/chunks/chunk-QV233D56.js:237:15)
    at async _SyncWrapper.executeQuery (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/alinea/dist/chunks/chunk-QV233D56.js:324:18) {
  [cause]: Error: no such savepoint: t127
      at Database.handleError (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/@alinea/sqlite-wasm/dist/load-module.js:1:5340)
      at ee.step (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/@alinea/sqlite-wasm/dist/load-module.js:1:1580)
      at ee.run (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/@alinea/sqlite-wasm/dist/load-module.js:1:2461)
      at PreparedStatement.run (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/alinea/dist/chunks/chunk-QV233D56.js:1428:15)
      at SyncPreparedStatementWrapper.run (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/alinea/dist/chunks/chunk-QV233D56.js:375:22)
      at Object.run (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/alinea/dist/chunks/chunk-QV233D56.js:232:27)
      at _SyncWrapper.executeQuery (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/alinea/dist/chunks/chunk-QV233D56.js:324:29)
      at _SyncWrapper.executeQuery (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/alinea/dist/chunks/chunk-QV233D56.js:398:18)
      at async _SyncWrapper.transaction (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/alinea/dist/chunks/chunk-QV233D56.js:345:7)
      at async _Database.fill (file:///home/brecht/projects/admin.codeurs.be-alinea/node_modules/alinea/dist/backend/Database.js:500:5)
}
```

**Comment by benmerckx** [comment]
This should be okay since 0.5.3
